
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 23 22:36:24 CET 2006
//----------------------------------------------------

package se.chalmers.cs.gf.Core;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _INTEGER_ = 24;
  public static final int _STRING_ = 23;
  public static final int _SYMB_19 = 21;
  public static final int _SYMB_18 = 20;
  public static final int _SYMB_17 = 19;
  public static final int CIdent = 27;
  public static final int _SYMB_16 = 18;
  public static final int _SYMB_15 = 17;
  public static final int _DOUBLE_ = 25;
  public static final int _SYMB_14 = 16;
  public static final int _SYMB_13 = 15;
  public static final int _SYMB_12 = 14;
  public static final int _SYMB_9 = 11;
  public static final int _SYMB_11 = 13;
  public static final int _SYMB_10 = 12;
  public static final int _SYMB_8 = 10;
  public static final int _SYMB_7 = 9;
  public static final int _SYMB_6 = 8;
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int EOF = 0;
  public static final int _SYMB_3 = 5;
  public static final int TMeta = 26;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int error = 1;
  public static final int _SYMB_20 = 22;
}

