package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class A extends ArgVar {
  public final String ident_;
  public final Integer integer_;

  public A(String p1, Integer p2) { ident_ = p1; integer_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.ArgVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.A) {
      se.chalmers.cs.gf.GFC.Absyn.A x = (se.chalmers.cs.gf.GFC.Absyn.A)o;
      return this.ident_.equals(x.ident_) && this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.integer_.hashCode();
  }


}
