package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class AbsDFun extends Def {
  public final String ident_;
  public final Exp exp_1, exp_2;

  public AbsDFun(String p1, Exp p2, Exp p3) { ident_ = p1; exp_1 = p2; exp_2 = p3; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.AbsDFun) {
      se.chalmers.cs.gf.GFC.Absyn.AbsDFun x = (se.chalmers.cs.gf.GFC.Absyn.AbsDFun)o;
      return this.ident_.equals(x.ident_) && this.exp_1.equals(x.exp_1) && this.exp_2.equals(x.exp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.exp_1.hashCode())+this.exp_2.hashCode();
  }


}
