package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public abstract class APatt implements java.io.Serializable {
  public abstract <R,A> R accept(APatt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFC.Absyn.APC p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.APV p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.APS p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.API p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.APF p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.APW p, A arg);

  }

}
