package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class APF extends APatt {
  public final Double double_;

  public APF(Double p1) { double_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.APatt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.APF) {
      se.chalmers.cs.gf.GFC.Absyn.APF x = (se.chalmers.cs.gf.GFC.Absyn.APF)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
