package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class AT extends Atom {
  public final Sort sort_;

  public AT(Sort p1) { sort_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Atom.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.AT) {
      se.chalmers.cs.gf.GFC.Absyn.AT x = (se.chalmers.cs.gf.GFC.Absyn.AT)o;
      return this.sort_.equals(x.sort_);
    }
    return false;
  }

  public int hashCode() {
    return this.sort_.hashCode();
  }


}
