package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class Cn extends CType {
  public final CIdent cident_;

  public Cn(CIdent p1) { cident_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.CType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.Cn) {
      se.chalmers.cs.gf.GFC.Absyn.Cn x = (se.chalmers.cs.gf.GFC.Absyn.Cn)o;
      return this.cident_.equals(x.cident_);
    }
    return false;
  }

  public int hashCode() {
    return this.cident_.hashCode();
  }


}
