package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFC.Absyn.EApp p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.EProd p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.EAbs p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.EAtom p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.EData p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.EEq p, A arg);

  }

}
