package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public abstract class Extend implements java.io.Serializable {
  public abstract <R,A> R accept(Extend.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFC.Absyn.Ext p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.NoExt p, A arg);

  }

}
