package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class KP extends Tokn {
  public final ListString liststring_;
  public final ListVariant listvariant_;

  public KP(ListString p1, ListVariant p2) { liststring_ = p1; listvariant_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Tokn.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.KP) {
      se.chalmers.cs.gf.GFC.Absyn.KP x = (se.chalmers.cs.gf.GFC.Absyn.KP)o;
      return this.liststring_.equals(x.liststring_) && this.listvariant_.equals(x.listvariant_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.liststring_.hashCode())+this.listvariant_.hashCode();
  }


}
