package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class LFlag extends Line {
  public final Flag flag_;

  public LFlag(Flag p1) { flag_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Line.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.LFlag) {
      se.chalmers.cs.gf.GFC.Absyn.LFlag x = (se.chalmers.cs.gf.GFC.Absyn.LFlag)o;
      return this.flag_.equals(x.flag_);
    }
    return false;
  }

  public int hashCode() {
    return this.flag_.hashCode();
  }


}
