package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class PC extends Patt {
  public final CIdent cident_;
  public final ListPatt listpatt_;

  public PC(CIdent p1, ListPatt p2) { cident_ = p1; listpatt_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Patt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.PC) {
      se.chalmers.cs.gf.GFC.Absyn.PC x = (se.chalmers.cs.gf.GFC.Absyn.PC)o;
      return this.cident_.equals(x.cident_) && this.listpatt_.equals(x.listpatt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.cident_.hashCode())+this.listpatt_.hashCode();
  }


}
