package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class PR extends Patt {
  public final ListPattAssign listpattassign_;

  public PR(ListPattAssign p1) { listpattassign_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Patt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.PR) {
      se.chalmers.cs.gf.GFC.Absyn.PR x = (se.chalmers.cs.gf.GFC.Absyn.PR)o;
      return this.listpattassign_.equals(x.listpattassign_);
    }
    return false;
  }

  public int hashCode() {
    return this.listpattassign_.hashCode();
  }


}
