package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class Table extends CType {
  public final CType ctype_1, ctype_2;

  public Table(CType p1, CType p2) { ctype_1 = p1; ctype_2 = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.CType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.Table) {
      se.chalmers.cs.gf.GFC.Absyn.Table x = (se.chalmers.cs.gf.GFC.Absyn.Table)o;
      return this.ctype_1.equals(x.ctype_1) && this.ctype_2.equals(x.ctype_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ctype_1.hashCode())+this.ctype_2.hashCode();
  }


}
