package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class TInts extends CType {
  public final Integer integer_;

  public TInts(Integer p1) { integer_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.CType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.TInts) {
      se.chalmers.cs.gf.GFC.Absyn.TInts x = (se.chalmers.cs.gf.GFC.Absyn.TInts)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
