
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 29 16:17:14 CEST 2005
//----------------------------------------------------

package se.chalmers.cs.gf.SyntaxTree;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _STRING_ = 4;
  public static final int _SYMB_1 = 3;
  public static final int error = 1;
  public static final int _IDENT_ = 6;
  public static final int _SYMB_0 = 2;
  public static final int _INTEGER_ = 5;
  public static final int EOF = 0;
}

