package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class EMeta extends Exp {
  public final String tmeta_;

  public EMeta(String p1) { tmeta_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.EMeta) {
      se.chalmers.cs.gf.Core.Absyn.EMeta x = (se.chalmers.cs.gf.Core.Absyn.EMeta)o;
      return this.tmeta_.equals(x.tmeta_);
    }
    return false;
  }

  public int hashCode() {
    return this.tmeta_.hashCode();
  }


}
