package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.Core.Absyn.ELet p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.ECase p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.EAbs p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.EPi p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.EApp p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.EProj p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.ERecType p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.ERec p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.EVar p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.EType p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.EStr p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.EInteger p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.EDouble p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.EMeta p, A arg);

  }

}
