package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public abstract class PatternVariable implements java.io.Serializable {
  public abstract <R,A> R accept(PatternVariable.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.Core.Absyn.PVVar p, A arg);
    public R visit(se.chalmers.cs.gf.Core.Absyn.PVWild p, A arg);

  }

}
