package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public abstract class Fun implements java.io.Serializable {
  public abstract <R,A> R accept(Fun.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.CFG.Absyn.Cons p, A arg);
    public R visit(se.chalmers.cs.gf.CFG.Absyn.Coerce p, A arg);

  }

}
