package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public class UnifyProfile extends Profile {
  public final ListInteger listinteger_;

  public UnifyProfile(ListInteger p1) { listinteger_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.CFG.Absyn.Profile.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.CFG.Absyn.UnifyProfile) {
      se.chalmers.cs.gf.CFG.Absyn.UnifyProfile x = (se.chalmers.cs.gf.CFG.Absyn.UnifyProfile)o;
      return this.listinteger_.equals(x.listinteger_);
    }
    return false;
  }

  public int hashCode() {
    return this.listinteger_.hashCode();
  }


}
