package se.chalmers.cs.gf.SyntaxTree.Absyn; // Java Package generated by the BNF Converter.

public abstract class Tr {
  public abstract <R,A> R accept(Tr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.SyntaxTree.Absyn.TNode p, A arg);
    public R visit(se.chalmers.cs.gf.SyntaxTree.Absyn.TAtom p, A arg);
    public R visit(se.chalmers.cs.gf.SyntaxTree.Absyn.TStr p, A arg);
    public R visit(se.chalmers.cs.gf.SyntaxTree.Absyn.TInt p, A arg);

  }

}
