package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public class AF extends Atom {
  public final Double double_;

  public AF(Double p1) { double_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFCC.Absyn.Atom.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFCC.Absyn.AF) {
      se.chalmers.cs.gf.GFCC.Absyn.AF x = (se.chalmers.cs.gf.GFCC.Absyn.AF)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
