package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public class W extends Term {
  public final String string_;
  public final Term term_;

  public W(String p1, Term p2) { string_ = p1; term_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFCC.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFCC.Absyn.W) {
      se.chalmers.cs.gf.GFCC.Absyn.W x = (se.chalmers.cs.gf.GFCC.Absyn.W)o;
      return this.string_.equals(x.string_) && this.term_.equals(x.term_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.string_.hashCode())+this.term_.hashCode();
  }


}
