package se.chalmers.cs.gf.MCFG.Absyn; // Java Package generated by the BNF Converter.

public class ArgProfileItem extends ProfileItem {
  public final Integer integer_;

  public ArgProfileItem(Integer p1) { integer_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.MCFG.Absyn.ProfileItem.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.MCFG.Absyn.ArgProfileItem) {
      se.chalmers.cs.gf.MCFG.Absyn.ArgProfileItem x = (se.chalmers.cs.gf.MCFG.Absyn.ArgProfileItem)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
