package se.chalmers.cs.gf.MCFG.Absyn; // Java Package generated by the BNF Converter.

public class MCFGM {
  public final ListMCFG listmcfg_;

  public MCFGM(ListMCFG p1) { listmcfg_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.MCFG.Absyn.MCFGM.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.MCFG.Absyn.MCFGM) {
      se.chalmers.cs.gf.MCFG.Absyn.MCFGM x = (se.chalmers.cs.gf.MCFG.Absyn.MCFGM)o;
      return this.listmcfg_.equals(x.listmcfg_);
    }
    return false;
  }

  public int hashCode() {
    return this.listmcfg_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.MCFG.Absyn.MCFGM p, A arg);

  }

}
