package se.chalmers.cs.gf.MCFG.Absyn; // Java Package generated by the BNF Converter.

public class MetaProfileItem extends ProfileItem {

  public MetaProfileItem() { }

  public <R,A> R accept(se.chalmers.cs.gf.MCFG.Absyn.ProfileItem.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.MCFG.Absyn.MetaProfileItem) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
