package se.chalmers.cs.gf.MCFG.Absyn; // Java Package generated by the BNF Converter.

public class Proj extends Sym {
  public final Cat cat_;
  public final Integer integer_;
  public final String ident_;

  public Proj(Cat p1, Integer p2, String p3) { cat_ = p1; integer_ = p2; ident_ = p3; }

  public <R,A> R accept(se.chalmers.cs.gf.MCFG.Absyn.Sym.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.MCFG.Absyn.Proj) {
      se.chalmers.cs.gf.MCFG.Absyn.Proj x = (se.chalmers.cs.gf.MCFG.Absyn.Proj)o;
      return this.cat_.equals(x.cat_) && this.integer_.equals(x.integer_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.cat_.hashCode())+this.integer_.hashCode())+this.ident_.hashCode();
  }


}
