package se.chalmers.cs.gf.MCFG.Absyn; // Java Package generated by the BNF Converter.

public class Term extends Sym {
  public final String string_;

  public Term(String p1) { string_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.MCFG.Absyn.Sym.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.MCFG.Absyn.Term) {
      se.chalmers.cs.gf.MCFG.Absyn.Term x = (se.chalmers.cs.gf.MCFG.Absyn.Term)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
