/* Function.java
 * Copyright (C) 2010 Grégoire Détrez, Ramona Enache
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package org.grammaticalframework.Trees.Absyn; // Java Package generated by the BNF Converter.

public class Function extends Tree {
    public final String ident_;
    
    public Function(String p1) { ident_ = p1; }

    public <R,A> R accept(org.grammaticalframework.Trees.Absyn.Tree.Visitor<R,A> v, A arg) { 
	return v.visit(this, arg);
    }

    public boolean equals(Object o) {
	if (this == o) return true;
	if (o instanceof org.grammaticalframework.Trees.Absyn.Function) {
	    org.grammaticalframework.Trees.Absyn.Function x = (org.grammaticalframework.Trees.Absyn.Function)o;
	    return this.ident_.equals(x.ident_);
	}
	return false;
    }
    
    public int hashCode() {
	return this.ident_.hashCode();
    }
    
    public String toString() {
	return this.ident_;
    }

}
