package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public class Cons extends Fun {
  public final String ident_;

  public Cons(String p1) { ident_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.CFG.Absyn.Fun.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.CFG.Absyn.Cons) {
      se.chalmers.cs.gf.CFG.Absyn.Cons x = (se.chalmers.cs.gf.CFG.Absyn.Cons)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
