package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public abstract class Flag implements java.io.Serializable {
  public abstract <R,A> R accept(Flag.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.CFG.Absyn.StartCat p, A arg);

  }

}
