package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public class Grammars {
  public final ListGrammar listgrammar_;

  public Grammars(ListGrammar p1) { listgrammar_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.CFG.Absyn.Grammars.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.CFG.Absyn.Grammars) {
      se.chalmers.cs.gf.CFG.Absyn.Grammars x = (se.chalmers.cs.gf.CFG.Absyn.Grammars)o;
      return this.listgrammar_.equals(x.listgrammar_);
    }
    return false;
  }

  public int hashCode() {
    return this.listgrammar_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.CFG.Absyn.Grammars p, A arg);

  }

}
