// This JLex file was machine-generated by the BNF converter
package se.chalmers.cs.gf.MCFG;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  public int line_num() { return (yyline+1); }
  public String buff() { return new String(yy_buffer,yy_buffer_index,10).trim(); }
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		38,
		38,
		38,
		38,
		40,
		42
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NOT_ACCEPT,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NOT_ACCEPT,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NOT_ACCEPT,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NOT_ACCEPT,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NOT_ACCEPT,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NOT_ACCEPT,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NOT_ACCEPT,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NO_ANCHOR,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NO_ANCHOR,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"28:9,33,25,28,33,25,28:18,33,28,27,28:4,24,28:4,11,3,2,28,29:10,5,1,28,6,4," +
"12,13,30:26,9,26,10,28,32,28,19,31,23,16,14,31,17,31:5,20,15,31:3,18,21,22," +
"31:6,7,28,8,28:66,30:23,28,30:7,31:24,28,31:8,28:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,53,
"0,1:11,2,1:2,3,1:3,4:3,1:8,5,6,7,4,8,9,10,11,12,13,14,15,16,17,18,19,20,21," +
"4,22,23,24,25")[0];

	private int yy_nxt[][] = unpackFromString(26,34,
"1,2,3,30,-1,32,4,5,6,7,8,9,10,11,12,48:2,51,48:3,52,48:2,34,13,-1,14,-1,15," +
"48:2,-1,13,-1:48,48,31,48:8,33,-1:4,33:2,48,33,-1:30,15,-1:18,48:10,33,-1:4" +
",33:2,48,33,-1:5,16,-1:43,48:2,19,48:7,33,-1:4,33:2,48,33,-1:7,17,-1:28,34:" +
"23,18,34,36,34:7,-1:14,48:5,37,48:4,33,-1:4,33:2,48,33,-1:25,34,-1,34,-1:21" +
",48:6,50,48:3,33,-1:4,33:2,48,33,-1,1,-1:47,48:4,41,48:5,33,-1:4,33:2,48,33" +
",-1,1,22:24,-1,23,24,22:6,-1:14,48:8,44,48,33,-1:4,33:2,48,33,-1,1,25:14,26" +
",25:6,27,25:2,-1,28,29,25:6,-1:14,48:5,45,48:4,33,-1:4,33:2,48,33,-1:15,48:" +
"9,46,33,-1:4,33:2,48,33,-1:15,48:4,20,48:5,33,-1:4,33:2,48,33,-1:15,48:5,47" +
",48:4,33,-1:4,33:2,48,33,-1:15,48:8,21,48,33,-1:4,33:2,48,33,-1:15,48:5,39," +
"48:4,33,-1:4,33:2,48,33,-1:15,48:6,43,48:3,33,-1:4,33:2,48,33,-1:15,48:4,35" +
",48:5,33,-1:4,33:2,48,33,-1:15,48:8,49,48,33,-1:4,33:2,48,33,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {
				return null;
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return new Symbol(sym._SYMB_0); }
					case -3:
						break;
					case 3:
						{ return new Symbol(sym._SYMB_1); }
					case -4:
						break;
					case 4:
						{ return new Symbol(sym._SYMB_10); }
					case -5:
						break;
					case 5:
						{ return new Symbol(sym._SYMB_4); }
					case -6:
						break;
					case 6:
						{ return new Symbol(sym._SYMB_5); }
					case -7:
						break;
					case 7:
						{ return new Symbol(sym._SYMB_6); }
					case -8:
						break;
					case 8:
						{ return new Symbol(sym._SYMB_7); }
					case -9:
						break;
					case 9:
						{ return new Symbol(sym._SYMB_8); }
					case -10:
						break;
					case 10:
						{ return new Symbol(sym._SYMB_9); }
					case -11:
						break;
					case 11:
						{ return new Symbol(sym._SYMB_11); }
					case -12:
						break;
					case 12:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -13:
						break;
					case 13:
						{ /* ignore white space. */ }
					case -14:
						break;
					case 14:
						{ yybegin(STRING); }
					case -15:
						break;
					case 15:
						{ return new Symbol(sym._INTEGER_, new Integer(yytext())); }
					case -16:
						break;
					case 16:
						{ return new Symbol(sym._SYMB_2); }
					case -17:
						break;
					case 17:
						{ return new Symbol(sym._SYMB_3); }
					case -18:
						break;
					case 18:
						{ return new Symbol(sym.SingleQuoteString, yytext().intern()); }
					case -19:
						break;
					case 19:
						{ return new Symbol(sym._SYMB_12); }
					case -20:
						break;
					case 20:
						{ return new Symbol(sym._SYMB_13); }
					case -21:
						break;
					case 21:
						{ return new Symbol(sym._SYMB_14); }
					case -22:
						break;
					case 22:
						{ pstring += yytext(); }
					case -23:
						break;
					case 23:
						{ yybegin(ESCAPED); }
					case -24:
						break;
					case 24:
						{ String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return new Symbol(sym._STRING_, foo.intern()); }
					case -25:
						break;
					case 25:
						{ pstring += yytext(); yybegin(STRING); }
					case -26:
						break;
					case 26:
						{ pstring +=  "\n"; yybegin(STRING); }
					case -27:
						break;
					case 27:
						{ pstring += "\t"; yybegin(STRING); }
					case -28:
						break;
					case 28:
						{ pstring += "\\"; yybegin(STRING); }
					case -29:
						break;
					case 29:
						{ pstring += "\""; yybegin(STRING); }
					case -30:
						break;
					case 31:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -31:
						break;
					case 33:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -32:
						break;
					case 35:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -33:
						break;
					case 37:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -34:
						break;
					case 39:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -35:
						break;
					case 41:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -36:
						break;
					case 43:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -37:
						break;
					case 44:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -38:
						break;
					case 45:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -39:
						break;
					case 46:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -40:
						break;
					case 47:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -41:
						break;
					case 48:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -42:
						break;
					case 49:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -43:
						break;
					case 50:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -44:
						break;
					case 51:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -45:
						break;
					case 52:
						{ return new Symbol(sym._IDENT_, yytext().intern()); }
					case -46:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
