package se.chalmers.cs.gf.MCFG.Absyn; // Java Package generated by the BNF Converter.

public class Cat {
  public final String singlequotestring_;

  public Cat(String p1) { singlequotestring_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.MCFG.Absyn.Cat.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.MCFG.Absyn.Cat) {
      se.chalmers.cs.gf.MCFG.Absyn.Cat x = (se.chalmers.cs.gf.MCFG.Absyn.Cat)o;
      return this.singlequotestring_.equals(x.singlequotestring_);
    }
    return false;
  }

  public int hashCode() {
    return this.singlequotestring_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.MCFG.Absyn.Cat p, A arg);

  }

}
