package se.chalmers.cs.gf.MCFG.Absyn; // Java Package generated by the BNF Converter.

public class Field {
  public final String ident_;
  public final ListSym listsym_;

  public Field(String p1, ListSym p2) { ident_ = p1; listsym_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.MCFG.Absyn.Field.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.MCFG.Absyn.Field) {
      se.chalmers.cs.gf.MCFG.Absyn.Field x = (se.chalmers.cs.gf.MCFG.Absyn.Field)o;
      return this.ident_.equals(x.ident_) && this.listsym_.equals(x.listsym_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.listsym_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.MCFG.Absyn.Field p, A arg);

  }

}
