package se.chalmers.cs.gf.MCFG.Absyn; // Java Package generated by the BNF Converter.

public class StartCat extends Flag {
  public final Cat cat_;

  public StartCat(Cat p1) { cat_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.MCFG.Absyn.Flag.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.MCFG.Absyn.StartCat) {
      se.chalmers.cs.gf.MCFG.Absyn.StartCat x = (se.chalmers.cs.gf.MCFG.Absyn.StartCat)o;
      return this.cat_.equals(x.cat_);
    }
    return false;
  }

  public int hashCode() {
    return this.cat_.hashCode();
  }


}
