module AbsTrees where

-- Haskell module generated by the BNF converter

newtype Ident = Ident String deriving (Eq,Ord,Show)
data Tree =
   Lambda Ident Tree
 | Variable Integer
 | Application Tree Tree
 | Literal Lit
 | MetaVariable Integer
 | Function Ident
  deriving (Eq,Ord,Show)

data Lit =
   IntLiteral Integer
 | FloatLiteral Double
 | StringLiteral String
  deriving (Eq,Ord,Show)

