package se.chalmers.cs.gf.MCFG.Absyn; // Java Package generated by the BNF Converter.

public abstract class ProfileItem implements java.io.Serializable {
  public abstract <R,A> R accept(ProfileItem.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.MCFG.Absyn.ArgProfileItem p, A arg);
    public R visit(se.chalmers.cs.gf.MCFG.Absyn.MetaProfileItem p, A arg);

  }

}
