package se.chalmers.cs.gf.MCFG.Absyn; // Java Package generated by the BNF Converter.

public class Profile {
  public final ListProfileItem listprofileitem_;

  public Profile(ListProfileItem p1) { listprofileitem_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.MCFG.Absyn.Profile.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.MCFG.Absyn.Profile) {
      se.chalmers.cs.gf.MCFG.Absyn.Profile x = (se.chalmers.cs.gf.MCFG.Absyn.Profile)o;
      return this.listprofileitem_.equals(x.listprofileitem_);
    }
    return false;
  }

  public int hashCode() {
    return this.listprofileitem_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.MCFG.Absyn.Profile p, A arg);

  }

}
