package se.chalmers.cs.gf.MCFG.Absyn; // Java Package generated by the BNF Converter.

public abstract class Sym implements java.io.Serializable {
  public abstract <R,A> R accept(Sym.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.MCFG.Absyn.Term p, A arg);
    public R visit(se.chalmers.cs.gf.MCFG.Absyn.Proj p, A arg);

  }

}
