
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 24 13:47:32 CEST 2010
//----------------------------------------------------

package org.grammaticalframework.Trees;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int EOF = 0;
  public static final int _IDENT_ = 11;
  public static final int _STRING_ = 8;
  public static final int error = 1;
  public static final int _INTEGER_ = 9;
  public static final int _DOUBLE_ = 10;
}

