package se.chalmers.cs.gf.SyntaxTree.Absyn; // Java Package generated by the BNF Converter.

public class TNode extends Tr implements java.io.Serializable
{
  public String ident_;
  public ListTr listtr_;

  public TNode(String p1, ListTr p2) { ident_ = p1; listtr_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.SyntaxTree.Absyn.Tr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }


}
