package Trees.Absyn; // Java Package generated by the BNF Converter.

public class Function extends Tree {
  public final String ident_;

  public Function(String p1) { ident_ = p1; }

  public <R,A> R accept(Trees.Absyn.Tree.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Trees.Absyn.Function) {
      Trees.Absyn.Function x = (Trees.Absyn.Function)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
