package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class EInteger extends Exp {
  public final Integer integer_;

  public EInteger(Integer p1) { integer_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.EInteger) {
      se.chalmers.cs.gf.Core.Absyn.EInteger x = (se.chalmers.cs.gf.Core.Absyn.EInteger)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
