package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class ELet extends Exp {
  public final ListLetDef listletdef_;
  public final Exp exp_;

  public ELet(ListLetDef p1, Exp p2) { listletdef_ = p1; exp_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.ELet) {
      se.chalmers.cs.gf.Core.Absyn.ELet x = (se.chalmers.cs.gf.Core.Absyn.ELet)o;
      return this.listletdef_.equals(x.listletdef_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listletdef_.hashCode())+this.exp_.hashCode();
  }


}
