package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class ERecType extends Exp {
  public final ListFieldType listfieldtype_;

  public ERecType(ListFieldType p1) { listfieldtype_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.ERecType) {
      se.chalmers.cs.gf.Core.Absyn.ERecType x = (se.chalmers.cs.gf.Core.Absyn.ERecType)o;
      return this.listfieldtype_.equals(x.listfieldtype_);
    }
    return false;
  }

  public int hashCode() {
    return this.listfieldtype_.hashCode();
  }


}
