package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class EType extends Exp {

  public EType() { }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.EType) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
