package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class Module {
  public final ListDecl listdecl_;

  public Module(ListDecl p1) { listdecl_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Module.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.Module) {
      se.chalmers.cs.gf.Core.Absyn.Module x = (se.chalmers.cs.gf.Core.Absyn.Module)o;
      return this.listdecl_.equals(x.listdecl_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdecl_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.Core.Absyn.Module p, A arg);

  }

}
