package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class PCons extends Pattern {
  public final String cident_;
  public final ListPattern listpattern_;

  public PCons(String p1, ListPattern p2) { cident_ = p1; listpattern_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.PCons) {
      se.chalmers.cs.gf.Core.Absyn.PCons x = (se.chalmers.cs.gf.Core.Absyn.PCons)o;
      return this.cident_.equals(x.cident_) && this.listpattern_.equals(x.listpattern_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.cident_.hashCode())+this.listpattern_.hashCode();
  }


}
