package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class PStr extends Pattern {
  public final String string_;

  public PStr(String p1) { string_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.PStr) {
      se.chalmers.cs.gf.Core.Absyn.PStr x = (se.chalmers.cs.gf.Core.Absyn.PStr)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
