package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class PVar extends Pattern {
  public final PatternVariable patternvariable_;

  public PVar(PatternVariable p1) { patternvariable_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.PVar) {
      se.chalmers.cs.gf.Core.Absyn.PVar x = (se.chalmers.cs.gf.Core.Absyn.PVar)o;
      return this.patternvariable_.equals(x.patternvariable_);
    }
    return false;
  }

  public int hashCode() {
    return this.patternvariable_.hashCode();
  }


}
