package org.grammaticalframework.Trees.Absyn; // Java Package generated by the BNF Converter.

public class IntLiteral extends Lit {
  public final Integer integer_;

  public IntLiteral(Integer p1) { integer_ = p1; }

  public <R,A> R accept(org.grammaticalframework.Trees.Absyn.Lit.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.grammaticalframework.Trees.Absyn.IntLiteral) {
      org.grammaticalframework.Trees.Absyn.IntLiteral x = (org.grammaticalframework.Trees.Absyn.IntLiteral)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
