package org.grammaticalframework.Trees.Absyn; // Java Package generated by the BNF Converter.

public abstract class Lit implements java.io.Serializable {
  public abstract <R,A> R accept(Lit.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(org.grammaticalframework.Trees.Absyn.IntLiteral p, A arg);
    public R visit(org.grammaticalframework.Trees.Absyn.FloatLiteral p, A arg);
    public R visit(org.grammaticalframework.Trees.Absyn.StringLiteral p, A arg);

  }

}
