package se.chalmers.cs.gf.SyntaxTree.Absyn; // Java Package generated by the BNF Converter.

public class TInt extends Tr implements java.io.Serializable
{
  public Integer integer_;

  public TInt(Integer p1) { integer_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.SyntaxTree.Absyn.Tr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }


}
