package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class AB extends ArgVar {
  public final String ident_;
  public final Integer integer_1, integer_2;

  public AB(String p1, Integer p2, Integer p3) { ident_ = p1; integer_1 = p2; integer_2 = p3; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.ArgVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.AB) {
      se.chalmers.cs.gf.GFC.Absyn.AB x = (se.chalmers.cs.gf.GFC.Absyn.AB)o;
      return this.ident_.equals(x.ident_) && this.integer_1.equals(x.integer_1) && this.integer_2.equals(x.integer_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.integer_1.hashCode())+this.integer_2.hashCode();
  }


}
