package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class APC extends APatt {
  public final CIdent cident_;
  public final ListAPatt listapatt_;

  public APC(CIdent p1, ListAPatt p2) { cident_ = p1; listapatt_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.APatt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.APC) {
      se.chalmers.cs.gf.GFC.Absyn.APC x = (se.chalmers.cs.gf.GFC.Absyn.APC)o;
      return this.cident_.equals(x.cident_) && this.listapatt_.equals(x.listapatt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.cident_.hashCode())+this.listapatt_.hashCode();
  }


}
