package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class EEq extends Exp {
  public final ListEquation listequation_;

  public EEq(ListEquation p1) { listequation_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.EEq) {
      se.chalmers.cs.gf.GFC.Absyn.EEq x = (se.chalmers.cs.gf.GFC.Absyn.EEq)o;
      return this.listequation_.equals(x.listequation_);
    }
    return false;
  }

  public int hashCode() {
    return this.listequation_.hashCode();
  }


}
