package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class Ext extends Extend {
  public final ListIdent listident_;

  public Ext(ListIdent p1) { listident_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Extend.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.Ext) {
      se.chalmers.cs.gf.GFC.Absyn.Ext x = (se.chalmers.cs.gf.GFC.Absyn.Ext)o;
      return this.listident_.equals(x.listident_);
    }
    return false;
  }

  public int hashCode() {
    return this.listident_.hashCode();
  }


}
