package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class Gr extends Canon {
  public final ListModule listmodule_;

  public Gr(ListModule p1) { listmodule_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Canon.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.Gr) {
      se.chalmers.cs.gf.GFC.Absyn.Gr x = (se.chalmers.cs.gf.GFC.Absyn.Gr)o;
      return this.listmodule_.equals(x.listmodule_);
    }
    return false;
  }

  public int hashCode() {
    return this.listmodule_.hashCode();
  }


}
