package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class LHeader extends Line {
  public final ModType modtype_;
  public final Extend extend_;
  public final Open open_;

  public LHeader(ModType p1, Extend p2, Open p3) { modtype_ = p1; extend_ = p2; open_ = p3; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Line.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.LHeader) {
      se.chalmers.cs.gf.GFC.Absyn.LHeader x = (se.chalmers.cs.gf.GFC.Absyn.LHeader)o;
      return this.modtype_.equals(x.modtype_) && this.extend_.equals(x.extend_) && this.open_.equals(x.open_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.modtype_.hashCode())+this.extend_.hashCode())+this.open_.hashCode();
  }


}
