package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class MTTrans extends ModType {
  public final String ident_1, ident_2, ident_3;

  public MTTrans(String p1, String p2, String p3) { ident_1 = p1; ident_2 = p2; ident_3 = p3; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.ModType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.MTTrans) {
      se.chalmers.cs.gf.GFC.Absyn.MTTrans x = (se.chalmers.cs.gf.GFC.Absyn.MTTrans)o;
      return this.ident_1.equals(x.ident_1) && this.ident_2.equals(x.ident_2) && this.ident_3.equals(x.ident_3);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_1.hashCode())+this.ident_2.hashCode())+this.ident_3.hashCode();
  }


}
