package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public abstract class Open implements java.io.Serializable {
  public abstract <R,A> R accept(Open.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFC.Absyn.Opens p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.NoOpens p, A arg);

  }

}
