package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class Par extends Term {
  public final CIdent cident_;
  public final ListTerm listterm_;

  public Par(CIdent p1, ListTerm p2) { cident_ = p1; listterm_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.Par) {
      se.chalmers.cs.gf.GFC.Absyn.Par x = (se.chalmers.cs.gf.GFC.Absyn.Par)o;
      return this.cident_.equals(x.cident_) && this.listterm_.equals(x.listterm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.cident_.hashCode())+this.listterm_.hashCode();
  }


}
