package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class PAss extends PattAssign {
  public final Label label_;
  public final Patt patt_;

  public PAss(Label p1, Patt p2) { label_ = p1; patt_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.PattAssign.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.PAss) {
      se.chalmers.cs.gf.GFC.Absyn.PAss x = (se.chalmers.cs.gf.GFC.Absyn.PAss)o;
      return this.label_.equals(x.label_) && this.patt_.equals(x.patt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.label_.hashCode())+this.patt_.hashCode();
  }


}
