package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public abstract class PattAssign implements java.io.Serializable {
  public abstract <R,A> R accept(PattAssign.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFC.Absyn.PAss p, A arg);

  }

}
