package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class PV extends Patt {
  public final String ident_;

  public PV(String p1) { ident_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Patt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.PV) {
      se.chalmers.cs.gf.GFC.Absyn.PV x = (se.chalmers.cs.gf.GFC.Absyn.PV)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
