package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class ResDPar extends Def {
  public final String ident_;
  public final ListParDef listpardef_;

  public ResDPar(String p1, ListParDef p2) { ident_ = p1; listpardef_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.ResDPar) {
      se.chalmers.cs.gf.GFC.Absyn.ResDPar x = (se.chalmers.cs.gf.GFC.Absyn.ResDPar)o;
      return this.ident_.equals(x.ident_) && this.listpardef_.equals(x.listpardef_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.listpardef_.hashCode();
  }


}
