package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class S extends Term {
  public final Term term_1, term_2;

  public S(Term p1, Term p2) { term_1 = p1; term_2 = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.S) {
      se.chalmers.cs.gf.GFC.Absyn.S x = (se.chalmers.cs.gf.GFC.Absyn.S)o;
      return this.term_1.equals(x.term_1) && this.term_2.equals(x.term_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.term_1.hashCode())+this.term_2.hashCode();
  }


}
