package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class T extends Term {
  public final CType ctype_;
  public final ListCase listcase_;

  public T(CType p1, ListCase p2) { ctype_ = p1; listcase_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.T) {
      se.chalmers.cs.gf.GFC.Absyn.T x = (se.chalmers.cs.gf.GFC.Absyn.T)o;
      return this.ctype_.equals(x.ctype_) && this.listcase_.equals(x.listcase_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ctype_.hashCode())+this.listcase_.hashCode();
  }


}
