package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public class Typ extends Type {
  public final ListCId listcid_;
  public final String cid_;

  public Typ(ListCId p1, String p2) { listcid_ = p1; cid_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFCC.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFCC.Absyn.Typ) {
      se.chalmers.cs.gf.GFCC.Absyn.Typ x = (se.chalmers.cs.gf.GFCC.Absyn.Typ)o;
      return this.listcid_.equals(x.listcid_) && this.cid_.equals(x.cid_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listcid_.hashCode())+this.cid_.hashCode();
  }


}
