package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public class AC extends Atom {
  public final String cid_;

  public AC(String p1) { cid_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFCC.Absyn.Atom.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFCC.Absyn.AC) {
      se.chalmers.cs.gf.GFCC.Absyn.AC x = (se.chalmers.cs.gf.GFCC.Absyn.AC)o;
      return this.cid_.equals(x.cid_);
    }
    return false;
  }

  public int hashCode() {
    return this.cid_.hashCode();
  }


}
