package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public class AM extends Atom {

  public AM() { }

  public <R,A> R accept(se.chalmers.cs.gf.GFCC.Absyn.Atom.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFCC.Absyn.AM) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
