package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public abstract class Atom implements java.io.Serializable {
  public abstract <R,A> R accept(Atom.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.AC p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.AS p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.AI p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.AF p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.AM p, A arg);

  }

}
