package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public class Hdr extends Header {
  public final String cid_;
  public final ListCId listcid_;

  public Hdr(String p1, ListCId p2) { cid_ = p1; listcid_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFCC.Absyn.Header.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFCC.Absyn.Hdr) {
      se.chalmers.cs.gf.GFCC.Absyn.Hdr x = (se.chalmers.cs.gf.GFCC.Absyn.Hdr)o;
      return this.cid_.equals(x.cid_) && this.listcid_.equals(x.listcid_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.cid_.hashCode())+this.listcid_.hashCode();
  }


}
