package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public abstract class Header implements java.io.Serializable {
  public abstract <R,A> R accept(Header.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.Hdr p, A arg);

  }

}
