package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public class KS extends Tokn {
  public final String string_;

  public KS(String p1) { string_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFCC.Absyn.Tokn.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFCC.Absyn.KS) {
      se.chalmers.cs.gf.GFCC.Absyn.KS x = (se.chalmers.cs.gf.GFCC.Absyn.KS)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
