package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public class S extends Term {
  public final ListTerm listterm_;

  public S(ListTerm p1) { listterm_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFCC.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFCC.Absyn.S) {
      se.chalmers.cs.gf.GFCC.Absyn.S x = (se.chalmers.cs.gf.GFCC.Absyn.S)o;
      return this.listterm_.equals(x.listterm_);
    }
    return false;
  }

  public int hashCode() {
    return this.listterm_.hashCode();
  }


}
