package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public abstract class Term implements java.io.Serializable {
  public abstract <R,A> R accept(Term.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.R p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.P p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.S p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.K p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.V p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.C p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.F p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.FV p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.W p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.RP p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.TM p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.L p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.BV p, A arg);

  }

}
