package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public abstract class Tokn implements java.io.Serializable {
  public abstract <R,A> R accept(Tokn.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.KS p, A arg);
    public R visit(se.chalmers.cs.gf.GFCC.Absyn.KP p, A arg);

  }

}
