package se.chalmers.cs.gf.GFCC.Absyn; // Java Package generated by the BNF Converter.

public class Var extends Variant {
  public final ListString liststring_1, liststring_2;

  public Var(ListString p1, ListString p2) { liststring_1 = p1; liststring_2 = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFCC.Absyn.Variant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFCC.Absyn.Var) {
      se.chalmers.cs.gf.GFCC.Absyn.Var x = (se.chalmers.cs.gf.GFCC.Absyn.Var)o;
      return this.liststring_1.equals(x.liststring_1) && this.liststring_2.equals(x.liststring_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.liststring_1.hashCode())+this.liststring_2.hashCode();
  }


}
