package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class AbsDCat extends Def {
  public final String ident_;
  public final ListDecl listdecl_;
  public final ListCIdent listcident_;

  public AbsDCat(String p1, ListDecl p2, ListCIdent p3) { ident_ = p1; listdecl_ = p2; listcident_ = p3; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.AbsDCat) {
      se.chalmers.cs.gf.GFC.Absyn.AbsDCat x = (se.chalmers.cs.gf.GFC.Absyn.AbsDCat)o;
      return this.ident_.equals(x.ident_) && this.listdecl_.equals(x.listdecl_) && this.listcident_.equals(x.listcident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.listdecl_.hashCode())+this.listcident_.hashCode();
  }


}
