package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class AC extends Atom {
  public final CIdent cident_;

  public AC(CIdent p1) { cident_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Atom.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.AC) {
      se.chalmers.cs.gf.GFC.Absyn.AC x = (se.chalmers.cs.gf.GFC.Absyn.AC)o;
      return this.cident_.equals(x.cident_);
    }
    return false;
  }

  public int hashCode() {
    return this.cident_.hashCode();
  }


}
