package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class APW extends APatt {

  public APW() { }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.APatt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.APW) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
