package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class Arg extends Term {
  public final ArgVar argvar_;

  public Arg(ArgVar p1) { argvar_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.Arg) {
      se.chalmers.cs.gf.GFC.Absyn.Arg x = (se.chalmers.cs.gf.GFC.Absyn.Arg)o;
      return this.argvar_.equals(x.argvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.argvar_.hashCode();
  }


}
