package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class AS extends Atom {
  public final String string_;

  public AS(String p1) { string_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Atom.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.AS) {
      se.chalmers.cs.gf.GFC.Absyn.AS x = (se.chalmers.cs.gf.GFC.Absyn.AS)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
