package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class Ass extends Assign {
  public final Label label_;
  public final Term term_;

  public Ass(Label p1, Term p2) { label_ = p1; term_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Assign.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.Ass) {
      se.chalmers.cs.gf.GFC.Absyn.Ass x = (se.chalmers.cs.gf.GFC.Absyn.Ass)o;
      return this.label_.equals(x.label_) && this.term_.equals(x.term_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.label_.hashCode())+this.term_.hashCode();
  }


}
