package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class AV extends Atom {
  public final String ident_;

  public AV(String p1) { ident_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Atom.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.AV) {
      se.chalmers.cs.gf.GFC.Absyn.AV x = (se.chalmers.cs.gf.GFC.Absyn.AV)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
