package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class Cas extends Case {
  public final ListPatt listpatt_;
  public final Term term_;

  public Cas(ListPatt p1, Term p2) { listpatt_ = p1; term_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Case.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.Cas) {
      se.chalmers.cs.gf.GFC.Absyn.Cas x = (se.chalmers.cs.gf.GFC.Absyn.Cas)o;
      return this.listpatt_.equals(x.listpatt_) && this.term_.equals(x.term_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listpatt_.hashCode())+this.term_.hashCode();
  }


}
