package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class CncDCat extends Def {
  public final String ident_;
  public final CType ctype_;
  public final Term term_1, term_2;

  public CncDCat(String p1, CType p2, Term p3, Term p4) { ident_ = p1; ctype_ = p2; term_1 = p3; term_2 = p4; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.CncDCat) {
      se.chalmers.cs.gf.GFC.Absyn.CncDCat x = (se.chalmers.cs.gf.GFC.Absyn.CncDCat)o;
      return this.ident_.equals(x.ident_) && this.ctype_.equals(x.ctype_) && this.term_1.equals(x.term_1) && this.term_2.equals(x.term_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.ident_.hashCode())+this.ctype_.hashCode())+this.term_1.hashCode())+this.term_2.hashCode();
  }


}
