package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public abstract class CType implements java.io.Serializable {
  public abstract <R,A> R accept(CType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFC.Absyn.RecType p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.Table p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.Cn p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.TStr p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.TInts p, A arg);

  }

}
