package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class EAtom extends Exp {
  public final Atom atom_;

  public EAtom(Atom p1) { atom_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.EAtom) {
      se.chalmers.cs.gf.GFC.Absyn.EAtom x = (se.chalmers.cs.gf.GFC.Absyn.EAtom)o;
      return this.atom_.equals(x.atom_);
    }
    return false;
  }

  public int hashCode() {
    return this.atom_.hashCode();
  }


}
