package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class Equ extends Equation {
  public final ListAPatt listapatt_;
  public final Exp exp_;

  public Equ(ListAPatt p1, Exp p2) { listapatt_ = p1; exp_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Equation.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.Equ) {
      se.chalmers.cs.gf.GFC.Absyn.Equ x = (se.chalmers.cs.gf.GFC.Absyn.Equ)o;
      return this.listapatt_.equals(x.listapatt_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listapatt_.hashCode())+this.exp_.hashCode();
  }


}
