package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class LMulti extends Line {
  public final ListIdent listident_;
  public final String ident_;

  public LMulti(ListIdent p1, String p2) { listident_ = p1; ident_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Line.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.LMulti) {
      se.chalmers.cs.gf.GFC.Absyn.LMulti x = (se.chalmers.cs.gf.GFC.Absyn.LMulti)o;
      return this.listident_.equals(x.listident_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listident_.hashCode())+this.ident_.hashCode();
  }


}
