package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class MGr extends Canon {
  public final ListIdent listident_;
  public final String ident_;
  public final ListModule listmodule_;

  public MGr(ListIdent p1, String p2, ListModule p3) { listident_ = p1; ident_ = p2; listmodule_ = p3; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Canon.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.MGr) {
      se.chalmers.cs.gf.GFC.Absyn.MGr x = (se.chalmers.cs.gf.GFC.Absyn.MGr)o;
      return this.listident_.equals(x.listident_) && this.ident_.equals(x.ident_) && this.listmodule_.equals(x.listmodule_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.listident_.hashCode())+this.ident_.hashCode())+this.listmodule_.hashCode();
  }


}
