package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class Mod extends Module {
  public final ModType modtype_;
  public final Extend extend_;
  public final Open open_;
  public final ListFlag listflag_;
  public final ListDef listdef_;

  public Mod(ModType p1, Extend p2, Open p3, ListFlag p4, ListDef p5) { modtype_ = p1; extend_ = p2; open_ = p3; listflag_ = p4; listdef_ = p5; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Module.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.Mod) {
      se.chalmers.cs.gf.GFC.Absyn.Mod x = (se.chalmers.cs.gf.GFC.Absyn.Mod)o;
      return this.modtype_.equals(x.modtype_) && this.extend_.equals(x.extend_) && this.open_.equals(x.open_) && this.listflag_.equals(x.listflag_) && this.listdef_.equals(x.listdef_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(this.modtype_.hashCode())+this.extend_.hashCode())+this.open_.hashCode())+this.listflag_.hashCode())+this.listdef_.hashCode();
  }


}
