package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public abstract class ModType implements java.io.Serializable {
  public abstract <R,A> R accept(ModType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFC.Absyn.MTAbs p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.MTCnc p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.MTRes p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.MTTrans p, A arg);

  }

}
