package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class P extends Term {
  public final Term term_;
  public final Label label_;

  public P(Term p1, Label p2) { term_ = p1; label_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.P) {
      se.chalmers.cs.gf.GFC.Absyn.P x = (se.chalmers.cs.gf.GFC.Absyn.P)o;
      return this.term_.equals(x.term_) && this.label_.equals(x.label_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.term_.hashCode())+this.label_.hashCode();
  }


}
