package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class ParD extends ParDef {
  public final String ident_;
  public final ListCType listctype_;

  public ParD(String p1, ListCType p2) { ident_ = p1; listctype_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.ParDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.ParD) {
      se.chalmers.cs.gf.GFC.Absyn.ParD x = (se.chalmers.cs.gf.GFC.Absyn.ParD)o;
      return this.ident_.equals(x.ident_) && this.listctype_.equals(x.listctype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.listctype_.hashCode();
  }


}
