package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public abstract class Patt implements java.io.Serializable {
  public abstract <R,A> R accept(Patt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFC.Absyn.PC p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.PV p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.PW p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.PR p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.PI p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.PF p, A arg);

  }

}
