package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class R extends Term {
  public final ListAssign listassign_;

  public R(ListAssign p1) { listassign_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.R) {
      se.chalmers.cs.gf.GFC.Absyn.R x = (se.chalmers.cs.gf.GFC.Absyn.R)o;
      return this.listassign_.equals(x.listassign_);
    }
    return false;
  }

  public int hashCode() {
    return this.listassign_.hashCode();
  }


}
