package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class RecType extends CType {
  public final ListLabelling listlabelling_;

  public RecType(ListLabelling p1) { listlabelling_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.CType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.RecType) {
      se.chalmers.cs.gf.GFC.Absyn.RecType x = (se.chalmers.cs.gf.GFC.Absyn.RecType)o;
      return this.listlabelling_.equals(x.listlabelling_);
    }
    return false;
  }

  public int hashCode() {
    return this.listlabelling_.hashCode();
  }


}
