package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class ResDOper extends Def {
  public final String ident_;
  public final CType ctype_;
  public final Term term_;

  public ResDOper(String p1, CType p2, Term p3) { ident_ = p1; ctype_ = p2; term_ = p3; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.ResDOper) {
      se.chalmers.cs.gf.GFC.Absyn.ResDOper x = (se.chalmers.cs.gf.GFC.Absyn.ResDOper)o;
      return this.ident_.equals(x.ident_) && this.ctype_.equals(x.ctype_) && this.term_.equals(x.term_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.ctype_.hashCode())+this.term_.hashCode();
  }


}
