package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public abstract class Status implements java.io.Serializable {
  public abstract <R,A> R accept(Status.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFC.Absyn.Canon p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.NonCan p, A arg);

  }

}
