package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public abstract class Term implements java.io.Serializable {
  public abstract <R,A> R accept(Term.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.GFC.Absyn.Arg p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.I p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.Par p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.LI p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.R p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.P p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.T p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.V p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.S p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.C p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.FV p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.EInt p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.EFloat p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.K p, A arg);
    public R visit(se.chalmers.cs.gf.GFC.Absyn.E p, A arg);

  }

}
