package se.chalmers.cs.gf.GFC.Absyn; // Java Package generated by the BNF Converter.

public class V extends Term {
  public final CType ctype_;
  public final ListTerm listterm_;

  public V(CType p1, ListTerm p2) { ctype_ = p1; listterm_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.GFC.Absyn.Term.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.GFC.Absyn.V) {
      se.chalmers.cs.gf.GFC.Absyn.V x = (se.chalmers.cs.gf.GFC.Absyn.V)o;
      return this.ctype_.equals(x.ctype_) && this.listterm_.equals(x.listterm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ctype_.hashCode())+this.listterm_.hashCode();
  }


}
