package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public class Category {
  public final String singlequotestring_;

  public Category(String p1) { singlequotestring_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.CFG.Absyn.Category.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.CFG.Absyn.Category) {
      se.chalmers.cs.gf.CFG.Absyn.Category x = (se.chalmers.cs.gf.CFG.Absyn.Category)o;
      return this.singlequotestring_.equals(x.singlequotestring_);
    }
    return false;
  }

  public int hashCode() {
    return this.singlequotestring_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.CFG.Absyn.Category p, A arg);

  }

}
