package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public class CatS extends Symbol {
  public final Category category_;

  public CatS(Category p1) { category_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.CFG.Absyn.Symbol.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.CFG.Absyn.CatS) {
      se.chalmers.cs.gf.CFG.Absyn.CatS x = (se.chalmers.cs.gf.CFG.Absyn.CatS)o;
      return this.category_.equals(x.category_);
    }
    return false;
  }

  public int hashCode() {
    return this.category_.hashCode();
  }


}
