package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public class ConstProfile extends Profile {
  public final String ident_;

  public ConstProfile(String p1) { ident_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.CFG.Absyn.Profile.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.CFG.Absyn.ConstProfile) {
      se.chalmers.cs.gf.CFG.Absyn.ConstProfile x = (se.chalmers.cs.gf.CFG.Absyn.ConstProfile)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
