package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public class Grammar {
  public final String ident_;
  public final ListFlag listflag_;
  public final ListRule listrule_;

  public Grammar(String p1, ListFlag p2, ListRule p3) { ident_ = p1; listflag_ = p2; listrule_ = p3; }

  public <R,A> R accept(se.chalmers.cs.gf.CFG.Absyn.Grammar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.CFG.Absyn.Grammar) {
      se.chalmers.cs.gf.CFG.Absyn.Grammar x = (se.chalmers.cs.gf.CFG.Absyn.Grammar)o;
      return this.ident_.equals(x.ident_) && this.listflag_.equals(x.listflag_) && this.listrule_.equals(x.listrule_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.listflag_.hashCode())+this.listrule_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.CFG.Absyn.Grammar p, A arg);

  }

}
