package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public class Profiles {
  public final ListProfile listprofile_;

  public Profiles(ListProfile p1) { listprofile_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.CFG.Absyn.Profiles.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.CFG.Absyn.Profiles) {
      se.chalmers.cs.gf.CFG.Absyn.Profiles x = (se.chalmers.cs.gf.CFG.Absyn.Profiles)o;
      return this.listprofile_.equals(x.listprofile_);
    }
    return false;
  }

  public int hashCode() {
    return this.listprofile_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.CFG.Absyn.Profiles p, A arg);

  }

}
