package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public abstract class Profile implements java.io.Serializable {
  public abstract <R,A> R accept(Profile.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.CFG.Absyn.UnifyProfile p, A arg);
    public R visit(se.chalmers.cs.gf.CFG.Absyn.ConstProfile p, A arg);

  }

}
