package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public abstract class Symbol implements java.io.Serializable {
  public abstract <R,A> R accept(Symbol.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(se.chalmers.cs.gf.CFG.Absyn.CatS p, A arg);
    public R visit(se.chalmers.cs.gf.CFG.Absyn.TermS p, A arg);

  }

}
