package se.chalmers.cs.gf.CFG.Absyn; // Java Package generated by the BNF Converter.

public class TermS extends Symbol {
  public final String string_;

  public TermS(String p1) { string_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.CFG.Absyn.Symbol.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.CFG.Absyn.TermS) {
      se.chalmers.cs.gf.CFG.Absyn.TermS x = (se.chalmers.cs.gf.CFG.Absyn.TermS)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
