/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.grammaticalframework.examples.phrasedroid;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon256=0x7f020000;
    }
    public static final class id {
        public static final int clear_button=0x7f060001;
        public static final int phrase_magnets=0x7f060000;
        public static final int result_view=0x7f060004;
        public static final int speak_button=0x7f060005;
        public static final int translate_button=0x7f060002;
        public static final int words_magnets=0x7f060003;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int phrasebook=0x7f040000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int default_sentence=0x7f050001;
        public static final int source_concrete=0x7f050002;
    }
}
