package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class EPi extends Exp {
  public final PatternVariable patternvariable_;
  public final Exp exp_1, exp_2;

  public EPi(PatternVariable p1, Exp p2, Exp p3) { patternvariable_ = p1; exp_1 = p2; exp_2 = p3; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.EPi) {
      se.chalmers.cs.gf.Core.Absyn.EPi x = (se.chalmers.cs.gf.Core.Absyn.EPi)o;
      return this.patternvariable_.equals(x.patternvariable_) && this.exp_1.equals(x.exp_1) && this.exp_2.equals(x.exp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.patternvariable_.hashCode())+this.exp_1.hashCode())+this.exp_2.hashCode();
  }


}
