package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class EProj extends Exp {
  public final Exp exp_;
  public final String cident_;

  public EProj(Exp p1, String p2) { exp_ = p1; cident_ = p2; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.EProj) {
      se.chalmers.cs.gf.Core.Absyn.EProj x = (se.chalmers.cs.gf.Core.Absyn.EProj)o;
      return this.exp_.equals(x.exp_) && this.cident_.equals(x.cident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_.hashCode())+this.cident_.hashCode();
  }


}
