package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class ERec extends Exp {
  public final ListFieldValue listfieldvalue_;

  public ERec(ListFieldValue p1) { listfieldvalue_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.ERec) {
      se.chalmers.cs.gf.Core.Absyn.ERec x = (se.chalmers.cs.gf.Core.Absyn.ERec)o;
      return this.listfieldvalue_.equals(x.listfieldvalue_);
    }
    return false;
  }

  public int hashCode() {
    return this.listfieldvalue_.hashCode();
  }


}
