package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class PInt extends Pattern {
  public final Integer integer_;

  public PInt(Integer p1) { integer_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.PInt) {
      se.chalmers.cs.gf.Core.Absyn.PInt x = (se.chalmers.cs.gf.Core.Absyn.PInt)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
