package se.chalmers.cs.gf.Core.Absyn; // Java Package generated by the BNF Converter.

public class PRec extends Pattern {
  public final ListFieldPattern listfieldpattern_;

  public PRec(ListFieldPattern p1) { listfieldpattern_ = p1; }

  public <R,A> R accept(se.chalmers.cs.gf.Core.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof se.chalmers.cs.gf.Core.Absyn.PRec) {
      se.chalmers.cs.gf.Core.Absyn.PRec x = (se.chalmers.cs.gf.Core.Absyn.PRec)o;
      return this.listfieldpattern_.equals(x.listfieldpattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.listfieldpattern_.hashCode();
  }


}
